name: AutoClicker CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8.1
    - name: Restore dependencies
      run: dotnet restore AutoClicker/AutoClicker.csproj
    - name: Build
      run: dotnet build --no-restore AutoClicker/AutoClicker.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal AutoClicker/AutoClicker.csproj
